import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Montserrat} from "next/font/google";

const montserratFont = Montserrat({
  subsets: ["latin"],
  weights: ["300", "400", "500", "600", "700"],
});
  

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={montserratFont.className}
      >
        {children}
      </body>
    </html>
  );
}
